[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PFT"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "numpy",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

[project.optional-dependencies]
io = [
  "czifile",
  "matplotlib",
  "imageio>=2.31",
  "scikit-image>=0.22",
  "ome-zarr>=0.12",
  "zarr>=3",
  "numcodecs",
  "dask",
]

ml = [
  "tensorflow",     # heavy -> keep optional
  "csbdeep",
  "n2v",
]

napari = [
  "napari",
]

cellpose = [
  "cellpose",
]

dev = [
  "pytest",
  "ruff",
  "black",
]
