from __future__ import annotations
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Literal
import numpy as np
import tifffile as tiff
import zarr

from PFT.core_prog_parts.denoising.fuji_managment import (
    find_project_root,
    ensure_fiji_in_project,
    ensure_deconvolutionlab2_exists,
)
from PFT.core_prog_parts.denoising.psf_creator import _find_java_exe
from PFT.core_prog_parts.decoder_omezar import (
    extract_ome_zarr_meta_for_compare,
    load_ome_zarr_3d_czyx,
)
from PFT.core_prog_parts.denoising.dl2 import run_dl2_cli, write_imagej_tiff_stack

PSFModel = Literal["BW", "GL", "RW"]

"Applies deconvolution directly to OME-Zarr-based image data"


DEFAULT_CHANNEL_WAVELENGTH_NM = {
    "TV1-T1-SR": 405.0,
    "TV1-T2-SR": 488.0,
    "TV1-T3-SR": 561.0,
}


@dataclass(frozen=True)
class DeconvRunInfo:
    in_zarr: Path
    out_zarr: Path
    out_dir: Path
    model: PSFModel
    iters: int
    background: float
    level: int
    out_dtype: str


def _dataset_path_for_level(zarr_dir: Path, level: int) -> str:
    """Return NGFF dataset path for a given pyramid level."""
    root = zarr.open_group(str(zarr_dir), mode="r")
    ms = root.attrs.get("multiscales")
    if not ms or not isinstance(ms, list) or not ms[0].get("datasets"):
        if level != 0:
            raise ValueError("No multiscales found; only level=0 is available for this OME-Zarr.")
        return "0"

    ds = ms[0]["datasets"]
    levels = list(range(len(ds)))
    if level not in levels:
        raise ValueError(f"Invalid level={level}. Available levels: {levels}")

    path = ds[level].get("path")
    if not isinstance(path, str) or not path:
        raise ValueError(f"Invalid dataset path for level={level}: {path!r}")
    return path


def _psf_path_for(*, model: PSFModel, channel_name: str, wavelength_nm: float, level: int, project_root: Path) -> Path:
    """
    PSF naming convention (generated by your PSF generator):
      psf_<MODEL>_<CHANNEL>_Lambda<NNN>nm__L<level>.tif
    """
    psf_dir = project_root / "results" / "psf" / "generated"
    return psf_dir / f"psf_{model}_{channel_name}_Lambda{int(round(wavelength_nm))}nm__L{int(level)}.tif"


def _ensure_empty_dir(p: Path) -> None:
    """Internal helper used by this module."""
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)


def _create_output_omezarr_single_scale_like_input(
    *,
    out_zarr: Path,
    in_meta: dict,
    shape_czyx: tuple[int, int, int, int],
    dtype: np.dtype,
    chunks_czyx: tuple[int, int, int, int] | None,
) -> zarr.Array:
    """
    Create output OME-Zarr as SINGLE-SCALE dataset "0".
    """
    if out_zarr.exists():
        shutil.rmtree(out_zarr)
    out_zarr.parent.mkdir(parents=True, exist_ok=True)

    root = zarr.open_group(str(out_zarr), mode="w")

    chunks = chunks_czyx or (1, 1, 256, 256)
    arr0 = root.create_dataset(
        "0",
        shape=shape_czyx,
        chunks=chunks,
        dtype=dtype,
        overwrite=True,
    )

    axes = str(in_meta.get("axes") or "czyx").lower()
    voxel = in_meta.get("voxel_size_um") or {"x": 1.0, "y": 1.0, "z": 1.0}

    scale_map = {
        "c": 1.0,
        "z": float(voxel.get("z") or 1.0),
        "y": float(voxel.get("y") or 1.0),
        "x": float(voxel.get("x") or 1.0),
    }
    scale_vec = [scale_map.get(a, 1.0) for a in axes]

    root.attrs["multiscales"] = [{
        "version": "0.4",
        "name": "image",
        "datasets": [{
            "path": "0",
            "coordinateTransformations": [{"type": "scale", "scale": scale_vec}],
        }],
        "axes": [{"name": a, "type": ("channel" if a == "c" else "space")} for a in axes],
    }]

    if in_meta.get("channel_names") is not None:
        root.attrs["channel_names"] = in_meta["channel_names"]

    return arr0


def _print_omezarr_meta(title: str, zarr_dir: Path, *, level: int) -> None:
    """Internal helper used by this module."""
    meta = extract_ome_zarr_meta_for_compare(zarr_dir, level=level)
    print(f"\n[{title}] OME-Zarr meta")
    print(f"  path         : {zarr_dir}")
    print(f"  level        : {level}")
    print(f"  array_path   : {meta.get('array_path')}")
    print(f"  stored shape : {meta.get('shape')}")
    print(f"  stored dtype : {meta.get('dtype')}")
    print(f"  stored chunks: {meta.get('chunks')}")
    print(f"  axes         : {meta.get('axes')}")
    print(f"  voxel_size_um: {meta.get('voxel_size_um')}")
    print(f"  channel_names: {meta.get('channel_names')}")


def _verify_on_disk_with_zarr(out_zarr: Path) -> None:
    """
    Most reliable check: re-open from disk and compute per-channel min/max.
    Avoids any caching behavior of downstream readers.
    """
    root = zarr.open_group(str(out_zarr), mode="r")
    arr0 = root["0"]

    mins: list[float] = []
    maxs: list[float] = []
    for c in range(arr0.shape[0]):
        slab = np.asarray(arr0[c, :, :, :])
        mins.append(float(slab.min()))
        maxs.append(float(slab.max()))

    print("\n[OUTPUT-ZARR-DISK-CHECK]")
    print(f"  dataset '0' dtype : {arr0.dtype}")
    print(f"  dataset '0' shape : {arr0.shape}")
    print(f"  per-channel min   : {[f'{v:.3g}' for v in mins]}")
    print(f"  per-channel max   : {[f'{v:.3g}' for v in maxs]}")
    print(f"  global min/max    : {min(mins):.3g} / {max(maxs):.3g}")


def _decode_and_print_output(title: str, zarr_dir: Path, *, level: int = 0) -> None:
    """
    Decoder-based check (ome-zarr reader). Useful, but on Windows it can show stale values immediately after writing.
    """
    vol, axes = load_ome_zarr_3d_czyx(zarr_dir, level=level, time=0, channels=None, as_numpy=True)
    print(f"\n[{title}] Decoded output (ome-zarr reader)")
    print(f"  decoded axes : {axes}")
    print(f"  decoded shape: {vol.shape}  (C,Z,Y,X)")
    print(f"  decoded dtype: {vol.dtype}")
    print(f"  decoded min/max: {float(vol.min()):.3g} / {float(vol.max()):.3g}")


def deconvolve_omezarr_3ch_to_omezarr(
    *,
    in_omezarr: Path,
    out_root: Path,
    model: PSFModel = "BW",
    iters: int = 15,
    background: float = 0.0,
    level: int = 0,
    channel_wavelength_nm: dict[str, float] | None = None,
    overwrite: bool = True,
) -> DeconvRunInfo:
   
    """Helper function used by this module."""
    in_omezarr = Path(in_omezarr)
    out_root = Path(out_root)
    channel_wavelength_nm = channel_wavelength_nm or dict(DEFAULT_CHANNEL_WAVELENGTH_NM)

    project_root = find_project_root(Path(__file__).resolve())

    # ---- Input meta print (chosen pyramid level) ----
    _print_omezarr_meta("INPUT", in_omezarr, level=level)

    dataset_path = _dataset_path_for_level(in_omezarr, level)
    root_in = zarr.open_group(str(in_omezarr), mode="r")
    arr_in = root_in[dataset_path]

    print(f"\n[INPUT] raw dataset")
    print(f"  dataset_path: {dataset_path}")
    print(f"  shape       : {arr_in.shape}")
    print(f"  dtype       : {arr_in.dtype}")

    if arr_in.ndim != 4:
        raise ValueError(
            f"Expected dataset '{dataset_path}' to be 4D (C,Z,Y,X) at level={level}. Got shape={arr_in.shape}"
        )

    c, z, y, x = arr_in.shape

    meta = extract_ome_zarr_meta_for_compare(in_omezarr, level=level)
    channel_names = meta.get("channel_names") or []
    if not isinstance(channel_names, list) or len(channel_names) < c:
        raise ValueError(f"Expected channel_names list length >= C. Got: {channel_names}")

    tag = in_omezarr.parent.name
    out_dir = out_root / f"{tag}__DL2_RL__PSF{model}__iter{iters}__L{int(level)}"
    out_zarr = out_dir / "image.ome.zarr"

    if overwrite:
        _ensure_empty_dir(out_dir)
    else:
        out_dir.mkdir(parents=True, exist_ok=True)
        if out_zarr.exists():
            raise FileExistsError(out_zarr)

    chunks_in = getattr(arr_in, "chunks", None)
    chunks_czyx = tuple(chunks_in) if chunks_in and len(chunks_in) == 4 else None

    arr_out = _create_output_omezarr_single_scale_like_input(
        out_zarr=out_zarr,
        in_meta=meta,
        shape_czyx=(c, z, y, x),
        dtype=np.dtype(np.float32),
        chunks_czyx=chunks_czyx,
    )

    print(f"\n[OUTPUT] created output OME-Zarr (float32)")
    print(f"  out_dir : {out_dir}")
    print(f"  out_zarr: {out_zarr}")
    print(f"  out dataset '0' shape: {arr_out.shape} dtype: {arr_out.dtype}")

    fiji_dir = ensure_fiji_in_project(project_root, quiet=True)
    dl2_jar = ensure_deconvolutionlab2_exists(fiji_dir, auto_download=True, quiet=True)
    java = _find_java_exe(fiji_dir)

    for ch_idx in range(c):
        ch_name = str(channel_names[ch_idx])
        if ch_name not in channel_wavelength_nm:
            raise KeyError(
                f"No wavelength mapping for channel '{ch_name}'. Provide channel_wavelength_nm mapping.\n"
                f"Known keys: {sorted(channel_wavelength_nm.keys())}"
            )

        lam = float(channel_wavelength_nm[ch_name])
        psf_path = _psf_path_for(
            model=model,
            channel_name=ch_name,
            wavelength_nm=lam,
            level=level,
            project_root=project_root,
        )
        if not psf_path.exists():
            raise FileNotFoundError(
                f"PSF not found: {psf_path}\n"
                f"Generate it first for model={model}, channel={ch_name}, lambda={lam}, level={level}."
            )

        vol_zyx = np.asarray(arr_in[ch_idx, :, :, :])  # (Z,Y,X)

        print(f"\n[CHANNEL {ch_idx}] {ch_name}")
        print(
            f"  input vol shape: {vol_zyx.shape} dtype={vol_zyx.dtype} "
            f"min={int(vol_zyx.min())} max={int(vol_zyx.max())}"
        )
        print(f"  PSF path: {psf_path}")

        with tempfile.TemporaryDirectory(prefix=f"pft_dl2_{tag}_L{level}_C{ch_idx}_") as td:
            td = Path(td)
            img_tif = td / f"{tag}__L{level}__C{ch_idx}__{ch_name}__image.tif"
            dl2_out = td / "dl2_out"
            dl2_out.mkdir(parents=True, exist_ok=True)

            write_imagej_tiff_stack(vol_zyx, img_tif, axes="ZYX")

            run_dl2_cli(
                java=java,
                dl2_jar=dl2_jar,
                image_tif=img_tif,
                psf_tif=psf_path,
                out_dir=dl2_out,
                iterations=iters,
                background=background,
            )

            outs = sorted(list(dl2_out.glob("*.tif")) + list(dl2_out.glob("*.tiff")))
            if not outs:
                raise FileNotFoundError(f"No TIFF output written by DL2 in {dl2_out}")

            out_tif = max(outs, key=lambda p: p.stat().st_size)
            deconv_zyx = tiff.imread(str(out_tif))

        print(
            f"  DL2 output: shape={deconv_zyx.shape} dtype={deconv_zyx.dtype} "
            f"min={float(deconv_zyx.min()):.3g} max={float(deconv_zyx.max()):.3g}"
        )

        if deconv_zyx.shape != (z, y, x):
            raise ValueError(f"DL2 output shape mismatch for channel {ch_idx}: {deconv_zyx.shape} vs {(z, y, x)}")

        f32 = np.ascontiguousarray(deconv_zyx.astype(np.float32))
        arr_out[ch_idx, :, :, :] = f32

        check = np.asarray(arr_out[ch_idx, :, :, :])
        print(
            f"  [WRITE CHECK] stored dtype={check.dtype} "
            f"min={float(check.min()):.3g} max={float(check.max()):.3g}"
        )

    _print_omezarr_meta("OUTPUT-STORED", out_zarr, level=0)
    _verify_on_disk_with_zarr(out_zarr)
    _decode_and_print_output("OUTPUT-DECODED", out_zarr, level=0)

    return DeconvRunInfo(
        in_zarr=in_omezarr,
        out_zarr=out_zarr,
        out_dir=out_dir,
        model=model,
        iters=iters,
        background=background,
        level=int(level),
        out_dtype="float32",
    )