"""
Train reproducible two-dimensional Noise2Void models from original OME-Zarr data.

The module is the core implementation used by
``scripts/denoising/train_n2v_2d.py``.  Training inputs are discovered only at
``results/img/<dataset>/<sample>/image.ome.zarr``.  Normalized TIFF files,
preview PNG files, masks, and prior N2V outputs are never considered.

The workflow performs an image-level train/validation split before patch
extraction.  Consequently, patches from one biological image cannot occur in
both partitions.  No intensity normalization is performed.  Level-0 source
values are converted to ``float32`` only because the N2V model requires a
floating-point input.

Important parameters
--------------------
``patch_shape``
    Spatial patch size. Larger patches include more context but increase GPU
    memory use. Values must fit within every selected source frame.
``num_patches_per_image``
    Requested number of random patches generated by N2V. More patches improve
    sampling but increase preparation time and storage in memory.
``validation_fraction``
    Fraction of complete source images reserved for validation. It controls the
    independence and precision of the validation-loss estimate.
``epochs``
    Number of complete training epochs. Too few can underfit; too many can
    overfit, which is detected when validation loss increases.
``batch_size``
    Number of patches processed per optimization step. Larger batches require
    more GPU memory and may smooth gradient updates.
``unet_n_first`` and ``unet_n_depth``
    U-Net width and depth. Larger values increase representational capacity,
    training time, and memory consumption.
``n2v_perc_pix``
    Percentage of pixels manipulated for blind-spot training. Increasing it
    supplies more supervised targets per patch but can alter optimization.
``n2v_neighborhood_radius``
    Radius used to sample replacement values around manipulated pixels. It
    should exceed the approximate correlation scale of the noise without
    extending beyond relevant local image context.
"""

from __future__ import annotations

import csv
from dataclasses import asdict, dataclass
import json
import math
from pathlib import Path
import shutil
from typing import Any, Iterable, Sequence

import matplotlib
matplotlib.use("Agg", force=True)
import matplotlib.pyplot as plt
import numpy as np
from n2v.internals.N2V_DataGenerator import N2V_DataGenerator
from n2v.models import N2V, N2VConfig

from PFT.core_prog_parts.decoder_omezar import ome_zarr_to_n2v_2d_stack
from PFT.core_prog_parts.denoising.n2v_workflow import (
    N2VModelSpec,
    discover_original_samples,
    get_model_spec,
    model_spec_as_dict,
    models_root,
    project_root,
    relative_or_absolute,
    source_array_properties,
    utc_now_iso,
)


@dataclass(frozen=True)
class N2VTrainingParameters:
    """Store all configurable model-training and patch-generation parameters."""

    patch_shape: tuple[int, int] = (64, 64)
    num_patches_per_image: int | None = 8192
    augment: bool = False
    shuffle_patches: bool = False
    validation_fraction: float = 0.20
    seed: int = 0
    epochs: int = 25
    batch_size: int = 128
    steps_per_epoch: int | None = None
    unet_kern_size: int = 3
    unet_n_first: int = 64
    unet_n_depth: int = 3
    train_loss: str = "mse"
    batch_norm: bool = True
    n2v_perc_pix: float = 0.198
    n2v_manipulator: str = "uniform_withCP"
    n2v_neighborhood_radius: int = 5
    single_net_per_channel: bool = False


PARAMETER_EXPLANATIONS: dict[str, str] = {
    "patch_shape": "Spatial YX patch size. Larger patches use more context and GPU memory.",
    "num_patches_per_image": "Requested patch sampling density. More patches increase coverage and preparation cost.",
    "augment": "Apply N2V geometric patch augmentation. It increases sample diversity.",
    "shuffle_patches": "Shuffle generated patches before training. The image split remains unchanged.",
    "validation_fraction": "Fraction of complete images reserved for validation before patch extraction.",
    "seed": "Random seed controlling the image split and patch preview selection.",
    "epochs": "Number of training epochs. Validation loss should be inspected for overfitting.",
    "batch_size": "Patches per optimizer update. Larger batches require more GPU memory.",
    "steps_per_epoch": "Optimizer steps per epoch. None computes ceil(train_patches / batch_size).",
    "unet_kern_size": "Convolution kernel width. Larger kernels observe a wider local neighborhood.",
    "unet_n_first": "Feature maps in the first U-Net level. Larger values increase capacity and memory use.",
    "unet_n_depth": "Number of U-Net down/up-sampling levels. Greater depth increases receptive field.",
    "train_loss": "Training objective. MSE penalizes squared prediction errors.",
    "batch_norm": "Use batch normalization in the U-Net.",
    "n2v_perc_pix": "Percentage of pixels selected as blind-spot targets in each patch.",
    "n2v_manipulator": "Rule used to replace blind-spot target pixels during training.",
    "n2v_neighborhood_radius": "Radius for replacement sampling around manipulated pixels.",
    "single_net_per_channel": "Whether separate networks are trained internally per channel for a joint input.",
}


@dataclass(frozen=True)
class SampleSplit:
    """Contain disjoint source-image partitions used for one model run."""

    train: tuple[Path, ...]
    validation: tuple[Path, ...]


@dataclass(frozen=True)
class TrainingResult:
    """Describe the completed training run and generated artifacts."""

    model_key: str
    model_name: str
    model_directory: Path
    artifact_directory: Path
    train_sample_count: int
    validation_sample_count: int
    train_patch_count: int
    validation_patch_count: int
    best_epoch: int | None
    best_validation_loss: float | None


def validate_training_parameters(parameters: N2VTrainingParameters) -> None:
    """Raise a clear error when a training parameter is outside its valid range.

    Args:
        parameters (N2VTrainingParameters): Value specifying parameters for the operation.

    Raises:
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> validate_training_parameters(parameters=...)
    """

    py, px = parameters.patch_shape
    if py <= 0 or px <= 0:
        raise ValueError("patch_shape values must be positive.")
    if parameters.num_patches_per_image is not None and parameters.num_patches_per_image <= 0:
        raise ValueError("num_patches_per_image must be positive or None.")
    if not 0.0 < parameters.validation_fraction < 1.0:
        raise ValueError("validation_fraction must be between zero and one.")
    if parameters.epochs <= 0:
        raise ValueError("epochs must be positive.")
    if parameters.batch_size <= 0:
        raise ValueError("batch_size must be positive.")
    if parameters.steps_per_epoch is not None and parameters.steps_per_epoch <= 0:
        raise ValueError("steps_per_epoch must be positive or None.")
    if parameters.unet_n_first <= 0 or parameters.unet_n_depth <= 0:
        raise ValueError("U-Net width and depth must be positive.")
    if not 0.0 < parameters.n2v_perc_pix <= 100.0:
        raise ValueError("n2v_perc_pix must be in the interval (0, 100].")
    if parameters.n2v_neighborhood_radius < 1:
        raise ValueError("n2v_neighborhood_radius must be at least one.")


def split_samples(
    samples: Sequence[Path], *, validation_fraction: float, seed: int
) -> SampleSplit:
    """Split complete source images into deterministic train and validation sets.

    At least one validation image is retained when two or more images are
    available.  A single-image dataset cannot provide an independent validation
    set and is rejected because its loss curve would be misleading.

    Args:
        samples (Sequence[Path]): Filesystem path used for samples.
        validation_fraction (float): Fraction of annotated samples reserved for validation.
        seed (int): Random seed used to make sampling, splitting, or initialization reproducible.

    Returns:
        SampleSplit: Result produced by the operation.

    Raises:
        RuntimeError: If the supplied inputs or runtime state violate the function's requirements.
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = split_samples(
        ...     samples=Path("path/to/resource"),
        ...     validation_fraction=0.5,
        ...     seed=1,
        ... )
    """

    resolved = tuple(sorted((Path(path).resolve() for path in samples), key=lambda item: str(item).lower()))
    if len(resolved) < 2:
        raise ValueError("N2V training requires at least two source images for an image-level validation split.")

    rng = np.random.default_rng(seed)
    indices = np.arange(len(resolved))
    rng.shuffle(indices)

    validation_count = int(round(len(resolved) * validation_fraction))
    validation_count = min(max(validation_count, 1), len(resolved) - 1)
    validation_indices = set(int(value) for value in indices[:validation_count])

    train = tuple(path for index, path in enumerate(resolved) if index not in validation_indices)
    validation = tuple(path for index, path in enumerate(resolved) if index in validation_indices)
    if set(train).intersection(validation):
        raise RuntimeError("Internal error: training and validation image sets overlap.")
    return SampleSplit(train=train, validation=validation)


def _ensure_nyxc(stack: np.ndarray) -> np.ndarray:
    """Convert an N2V stack to the required ``N,Y,X,C`` layout.

    Args:
        stack (np.ndarray): Image stack containing multiple slices, channels, or time points.

    Returns:
        np.ndarray: Array containing the processed result.

    Raises:
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = _ensure_nyxc(stack=image_array)
    """

    array = np.asarray(stack)
    if array.ndim == 2:
        return array[None, ..., None]
    if array.ndim == 3:
        return array[..., None]
    if array.ndim == 4:
        return array
    raise ValueError(f"Unexpected N2V stack shape: {array.shape}")


def load_model_frames(samples: Sequence[Path], spec: N2VModelSpec) -> list[np.ndarray]:
    """Load original level-0 frames required by one model without normalization.

    Single-channel models return ``Y,X`` frames.  The joint model returns
    ``Y,X,2`` frames with channels ordered as DAPI then WGA.

    Args:
        samples (Sequence[Path]): Filesystem path used for samples.
        spec (N2VModelSpec): Value specifying spec for the operation.

    Returns:
        list[np.ndarray]: Collection containing the generated or selected values.

    Raises:
        RuntimeError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = load_model_frames(samples=Path("path/to/resource"), spec=...)
    """

    frames: list[np.ndarray] = []
    for sample in samples:
        if spec.joint:
            channel_stacks = [
                _ensure_nyxc(
                    ome_zarr_to_n2v_2d_stack(
                        sample,
                        channel=channel,
                        time=None,
                        z=None,
                        normalize=None,
                    )
                )
                for channel in spec.channels
            ]
            frame_count = min(stack.shape[0] for stack in channel_stacks)
            if len({stack.shape[0] for stack in channel_stacks}) != 1:
                print(f"[WARN] {sample.parent.name}: channel frame counts differ; using {frame_count} frames.")
            for frame_index in range(frame_count):
                frames.append(
                    np.concatenate(
                        [stack[frame_index] for stack in channel_stacks], axis=-1
                    ).astype(np.float32, copy=False)
                )
        else:
            stack = _ensure_nyxc(
                ome_zarr_to_n2v_2d_stack(
                    sample,
                    channel=spec.channels[0],
                    time=None,
                    z=None,
                    normalize=None,
                )
            )
            for frame_index in range(stack.shape[0]):
                frames.append(stack[frame_index, ..., 0].astype(np.float32, copy=False))
    if not frames:
        raise RuntimeError(f"No frames were loaded for model {spec.key!r}.")
    return frames


def frames_to_syxc(frames: Sequence[np.ndarray]) -> tuple[np.ndarray, int, tuple[int, int]]:
    """Stack equally sized frames into ``S,Y,X,C`` and count skipped frames.

    The most common YX size is selected.  Frames with another size are skipped
    and reported because N2V patch generation requires one rectangular array.

    Args:
        frames (Sequence[np.ndarray]): Array containing frames.

    Returns:
        tuple[np.ndarray, int, tuple[int, int]]: Collection containing the generated or selected values.

    Raises:
        RuntimeError: If the supplied inputs or runtime state violate the function's requirements.
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = frames_to_syxc(frames=image_array)
    """

    if not frames:
        raise ValueError("No frames were supplied.")
    sizes = [(int(frame.shape[0]), int(frame.shape[1])) for frame in frames]
    counts: dict[tuple[int, int], int] = {}
    for size in sizes:
        counts[size] = counts.get(size, 0) + 1
    target_size = max(counts, key=lambda size: (counts[size], size))

    kept: list[np.ndarray] = []
    skipped = 0
    for frame in frames:
        if frame.ndim not in (2, 3) or tuple(frame.shape[:2]) != target_size:
            skipped += 1
            continue
        kept.append(frame[..., None] if frame.ndim == 2 else frame)
    if not kept:
        raise RuntimeError("All frames were skipped because their dimensions were incompatible.")
    return np.stack(kept).astype(np.float32, copy=False), skipped, target_size


def generate_patches(
    frames: Sequence[np.ndarray], *, parameters: N2VTrainingParameters
) -> tuple[np.ndarray, dict[str, Any]]:
    """Generate N2V patches from one image partition and return a data summary.

    Args:
        frames (Sequence[np.ndarray]): Array containing frames.
        parameters (N2VTrainingParameters): Value specifying parameters for the operation.

    Returns:
        tuple[np.ndarray, dict[str, Any]]: Mapping containing the generated or resolved values.

    Raises:
        RuntimeError: If the supplied inputs or runtime state violate the function's requirements.
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = generate_patches(frames=image_array, parameters=...)
    """

    syxc, skipped, target_size = frames_to_syxc(frames)
    py, px = parameters.patch_shape
    if target_size[0] < py or target_size[1] < px:
        raise ValueError(
            f"Patch shape {parameters.patch_shape} exceeds source frame size {target_size}."
        )

    generator = N2V_DataGenerator()
    patches = generator.generate_patches_from_list(
        [syxc],
        num_patches_per_img=parameters.num_patches_per_image,
        shape=tuple(parameters.patch_shape),
        augment=bool(parameters.augment),
        shuffle=bool(parameters.shuffle_patches),
    )
    patches = np.asarray(patches, dtype=np.float32)
    if patches.ndim == 3:
        patches = patches[..., None]
    if patches.ndim != 4:
        raise ValueError(f"Unexpected generated patch shape: {patches.shape}")
    if patches.shape[0] == 0:
        raise RuntimeError("N2V generated zero patches.")

    summary = {
        "source_frame_count": int(len(frames)),
        "kept_frame_count": int(syxc.shape[0]),
        "skipped_frame_count": int(skipped),
        "target_frame_shape_yx": [int(value) for value in target_size],
        "source_stack_shape_syxc": [int(value) for value in syxc.shape],
        "patch_shape_nyxc": [int(value) for value in patches.shape],
        "dtype": str(patches.dtype),
        "minimum": float(np.min(patches)),
        "maximum": float(np.max(patches)),
        "mean": float(np.mean(patches)),
        "standard_deviation": float(np.std(patches)),
        "normalization": "none",
    }
    return patches, summary


def build_n2v_config(
    train_patches: np.ndarray, parameters: N2VTrainingParameters
) -> tuple[N2VConfig, int]:
    """Create an N2V configuration and return the effective steps per epoch.

    Args:
        train_patches (np.ndarray): Array containing train patches.
        parameters (N2VTrainingParameters): Value specifying parameters for the operation.

    Returns:
        tuple[N2VConfig, int]: Collection containing the generated or selected values.

    Example:
        >>> result = build_n2v_config(train_patches=image_array, parameters=...)
    """

    steps = parameters.steps_per_epoch
    if steps is None:
        steps = max(1, int(math.ceil(train_patches.shape[0] / parameters.batch_size)))
    config = N2VConfig(
        train_patches,
        unet_kern_size=parameters.unet_kern_size,
        unet_n_first=parameters.unet_n_first,
        unet_n_depth=parameters.unet_n_depth,
        train_steps_per_epoch=int(steps),
        train_epochs=parameters.epochs,
        train_loss=parameters.train_loss,
        batch_norm=parameters.batch_norm,
        train_batch_size=parameters.batch_size,
        n2v_perc_pix=parameters.n2v_perc_pix,
        n2v_patch_shape=tuple(parameters.patch_shape),
        n2v_manipulator=parameters.n2v_manipulator,
        n2v_neighborhood_radius=parameters.n2v_neighborhood_radius,
        single_net_per_channel=parameters.single_net_per_channel,
    )
    return config, int(steps)


def _write_json(path: Path, value: Any) -> None:
    """Write an indented UTF-8 JSON file, creating its parent directory.

    Args:
        path (Path): Filesystem path to the required input or output resource.
        value (Any): Value to validate, transform, store, or forward.

    Example:
        >>> _write_json(path=Path("path/to/resource"), value=...)
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False), encoding="utf-8")


def save_sample_split(
    split: SampleSplit, *, artifact_dir: Path, repo_root: Path, spec: N2VModelSpec
) -> None:
    """Save image-level train/validation membership as CSV and JSON.

    Args:
        split (SampleSplit): Value specifying split for the operation.
        artifact_dir (Path): Directory used for artifact.
        repo_root (Path): Directory used for repo.
        spec (N2VModelSpec): Value specifying spec for the operation.

    Example:
        >>> save_sample_split(
        ...     split=...,
        ...     artifact_dir=Path("path/to/resource"),
        ...     repo_root=Path("path/to/resource"),
        ...     spec=...,
        ... )
    """

    records: list[dict[str, Any]] = []
    for partition, paths in (("train", split.train), ("validation", split.validation)):
        for path in paths:
            properties = source_array_properties(path)
            records.append(
                {
                    "partition": partition,
                    "model_key": spec.key,
                    "dataset": spec.dataset,
                    "sample": path.parent.name,
                    "zarr_path": relative_or_absolute(path, repo_root),
                    "axes": properties["axes"],
                    "shape": properties["shape"],
                    "dtype": properties["dtype"],
                    "channels_used": list(spec.channels),
                    "normalization": "none",
                    "source_attrs_sha256": properties["attrs_sha256"],
                }
            )

    csv_path = artifact_dir / "sample_split.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(records[0]))
        writer.writeheader()
        for record in records:
            csv_record = dict(record)
            csv_record["shape"] = json.dumps(csv_record["shape"])
            csv_record["channels_used"] = json.dumps(csv_record["channels_used"])
            writer.writerow(csv_record)
    _write_json(artifact_dir / "sample_split.json", records)


def save_patch_previews(
    patches: np.ndarray, *, artifact_dir: Path, seed: int, prefix: str
) -> None:
    """Save two raw-range patch previews without changing training values.

    Args:
        patches (np.ndarray): Array containing patches.
        artifact_dir (Path): Directory used for artifact.
        seed (int): Random seed used to make sampling, splitting, or initialization reproducible.
        prefix (str): Text value specifying prefix.

    Example:
        >>> save_patch_previews(
        ...     patches=image_array,
        ...     artifact_dir=Path("path/to/resource"),
        ...     seed=1,
        ...     prefix="prefix",
        ... )
    """

    preview_dir = artifact_dir / "patch_previews"
    preview_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)
    count = min(2, patches.shape[0])
    indices = rng.choice(patches.shape[0], size=count, replace=False)
    for number, index in enumerate(indices, start=1):
        patch = patches[int(index)]
        channel_count = patch.shape[-1]
        fig = plt.figure(figsize=(5 * channel_count, 5), constrained_layout=True)
        for channel in range(channel_count):
            axis = fig.add_subplot(1, channel_count, channel + 1)
            axis.imshow(patch[..., channel], cmap="gray")
            axis.set_title(f"{prefix}: patch {int(index)}, channel {channel}")
            axis.axis("off")
        fig.savefig(preview_dir / f"patch_{number:02d}.png", dpi=200)
        plt.close(fig)


def history_dictionary(history: Any) -> dict[str, list[float]]:
    """Convert a Keras/N2V history object to serializable float lists.

    Args:
        history (Any): Value specifying history for the operation.

    Returns:
        dict[str, list[float]]: Mapping containing the generated or resolved values.

    Raises:
        TypeError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = history_dictionary(history=...)
    """

    raw = getattr(history, "history", history)
    if not isinstance(raw, dict):
        raise TypeError("N2V training did not return a dictionary-like history.")
    converted: dict[str, list[float]] = {}
    for key, values in raw.items():
        converted[str(key)] = [float(value) for value in values]
    return converted


def save_training_history(history: Any, artifact_dir: Path) -> tuple[int | None, float | None]:
    """Save numeric training history and PNG/PDF loss curves.

    The best epoch is selected by minimum ``val_loss`` when available, otherwise
    by minimum training ``loss``.

    Args:
        history (Any): Value specifying history for the operation.
        artifact_dir (Path): Directory used for artifact.

    Returns:
        tuple[int | None, float | None]: Collection containing the generated or selected values.

    Example:
        >>> result = save_training_history(history=..., artifact_dir=Path("path/to/resource"))
    """

    history_data = history_dictionary(history)
    _write_json(artifact_dir / "training_history.json", history_data)

    row_count = max((len(values) for values in history_data.values()), default=0)
    keys = list(history_data)
    with (artifact_dir / "training_history.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["epoch", *keys])
        writer.writeheader()
        for index in range(row_count):
            row: dict[str, Any] = {"epoch": index + 1}
            for key in keys:
                row[key] = history_data[key][index] if index < len(history_data[key]) else ""
            writer.writerow(row)

    fig = plt.figure(figsize=(8, 5), constrained_layout=True)
    axis = fig.add_subplot(1, 1, 1)
    plotted = False
    for key in ("loss", "val_loss"):
        values = history_data.get(key)
        if values:
            axis.plot(range(1, len(values) + 1), values, label=key)
            plotted = True
    if not plotted:
        for key, values in history_data.items():
            if values:
                axis.plot(range(1, len(values) + 1), values, label=key)
    axis.set_xlabel("Epoch")
    axis.set_ylabel("Loss")
    axis.set_title("Noise2Void training history")
    axis.grid(True, alpha=0.3)
    if axis.lines:
        axis.legend()
    fig.savefig(artifact_dir / "training_curves.png", dpi=300)
    fig.savefig(artifact_dir / "training_curves.pdf")
    plt.close(fig)

    selection_key = "val_loss" if history_data.get("val_loss") else "loss"
    values = history_data.get(selection_key, [])
    if not values:
        return None, None
    best_index = int(np.argmin(np.asarray(values, dtype=np.float64)))
    return best_index + 1, float(values[best_index])


def _parameter_payload(parameters: N2VTrainingParameters, effective_steps: int) -> dict[str, Any]:
    """Create a parameter file containing values and scientific interpretation.

    Args:
        parameters (N2VTrainingParameters): Value specifying parameters for the operation.
        effective_steps (int): Numerical value controlling effective steps.

    Returns:
        dict[str, Any]: Mapping containing the generated or resolved values.

    Example:
        >>> result = _parameter_payload(parameters=..., effective_steps=1)
    """

    values = asdict(parameters)
    values["patch_shape"] = list(parameters.patch_shape)
    values["effective_steps_per_epoch"] = effective_steps
    return {
        "generated_utc": utc_now_iso(),
        "values": values,
        "explanations": PARAMETER_EXPLANATIONS,
        "input_normalization": "none",
        "input_cast": "original level-0 values converted to float32",
    }


def train_model(
    model_key: str,
    *,
    parameters: N2VTrainingParameters | None = None,
    repo_root: Path | None = None,
    overwrite_model: bool = False,
) -> TrainingResult:
    """Train one selected N2V model and save complete reproducibility artifacts.

    Args:
        model_key (str): Text value specifying model key.
        parameters (N2VTrainingParameters | None): Value specifying parameters for the operation. ``None`` selects the function's default behavior.
        repo_root (Path | None): Directory used for repo. ``None`` selects the function's default behavior.
        overwrite_model (bool): Boolean flag controlling overwrite model. Defaults to ``False``.

    Returns:
        TrainingResult: Result produced by the operation.

    Raises:
        FileExistsError: If the supplied inputs or runtime state violate the function's requirements.
        FileNotFoundError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = train_model(model_key="model_key")
    """

    params = parameters or N2VTrainingParameters()
    validate_training_parameters(params)
    spec = get_model_spec(model_key)
    root = (repo_root or project_root()).resolve()
    samples = discover_original_samples(spec, root)
    if not samples:
        expected = root / "results" / "img" / spec.dataset
        raise FileNotFoundError(
            f"No original image.ome.zarr inputs found below {expected}. "
            "Training intentionally does not read results/training_files."
        )

    split = split_samples(
        samples,
        validation_fraction=params.validation_fraction,
        seed=params.seed,
    )
    train_frames = load_model_frames(split.train, spec)
    validation_frames = load_model_frames(split.validation, spec)
    train_patches, train_patch_summary = generate_patches(train_frames, parameters=params)
    validation_patches, validation_patch_summary = generate_patches(validation_frames, parameters=params)

    model_base = models_root(root)
    model_base.mkdir(parents=True, exist_ok=True)
    model_dir = model_base / spec.model_name
    if model_dir.exists() and any(model_dir.iterdir()):
        if not overwrite_model:
            raise FileExistsError(
                f"Model directory already exists: {model_dir}. "
                "Use --overwrite-model only when retraining should replace it."
            )
        shutil.rmtree(model_dir)

    config, effective_steps = build_n2v_config(train_patches, params)
    model = N2V(config, spec.model_name, basedir=str(model_base))
    artifact_dir = model_dir / "pft_training"
    artifact_dir.mkdir(parents=True, exist_ok=True)

    save_sample_split(split, artifact_dir=artifact_dir, repo_root=root, spec=spec)
    _write_json(artifact_dir / "model_spec.json", model_spec_as_dict(spec))
    _write_json(
        artifact_dir / "training_parameters.json",
        _parameter_payload(params, effective_steps),
    )
    _write_json(
        artifact_dir / "patch_summary.json",
        {
            "generated_utc": utc_now_iso(),
            "train": train_patch_summary,
            "validation": validation_patch_summary,
            "partitions_created_before_patch_generation": True,
            "partition_overlap": False,
        },
    )
    save_patch_previews(
        train_patches,
        artifact_dir=artifact_dir,
        seed=params.seed,
        prefix=f"{spec.model_name} training",
    )

    print("\n========== N2V TRAINING ==========")
    print(f"Model key:             {spec.key}")
    print(f"Model name:            {spec.model_name}")
    print(f"Dataset:               {spec.dataset}")
    print(f"Source root:           {root / 'results' / 'img' / spec.dataset}")
    print(f"Channels:              {list(spec.channels)}")
    print(f"Train images:          {len(split.train)}")
    print(f"Validation images:     {len(split.validation)}")
    print(f"Train patches:         {train_patches.shape}")
    print(f"Validation patches:    {validation_patches.shape}")
    print("Input normalization:   none")
    print(f"Steps per epoch:       {effective_steps}")
    print(f"Epochs:                {params.epochs}")
    print(f"Artifacts:             {artifact_dir}")
    print("==================================\n")

    try:
        keras_model = getattr(model, "keras_model", None)
        if keras_model is not None:
            keras_model.summary()
    except Exception as exc:
        print(f"[WARN] Could not print Keras model summary: {exc}")

    history = model.train(train_patches, validation_patches)
    best_epoch, best_validation_loss = save_training_history(history, artifact_dir)

    summary_lines = [
        "PFT 2D Noise2Void training summary",
        "=" * 72,
        f"Generated (UTC): {utc_now_iso()}",
        f"Model key: {spec.key}",
        f"Model name: {spec.model_name}",
        f"Dataset: {spec.dataset}",
        f"Source directory: {root / 'results' / 'img' / spec.dataset}",
        f"Source channels: {list(spec.channels)}",
        f"Input normalization: none",
        f"Training images: {len(split.train)}",
        f"Validation images: {len(split.validation)}",
        f"Training patches: {train_patches.shape[0]}",
        f"Validation patches: {validation_patches.shape[0]}",
        f"Best epoch: {best_epoch if best_epoch is not None else '-'}",
        f"Best validation/loss value: {best_validation_loss if best_validation_loss is not None else '-'}",
        f"Model directory: {model_dir}",
        f"Artifact directory: {artifact_dir}",
    ]
    (artifact_dir / "training_summary.txt").write_text("\n".join(summary_lines) + "\n", encoding="utf-8")

    return TrainingResult(
        model_key=spec.key,
        model_name=spec.model_name,
        model_directory=model_dir,
        artifact_directory=artifact_dir,
        train_sample_count=len(split.train),
        validation_sample_count=len(split.validation),
        train_patch_count=int(train_patches.shape[0]),
        validation_patch_count=int(validation_patches.shape[0]),
        best_epoch=best_epoch,
        best_validation_loss=best_validation_loss,
    )
