r"""Provide command-line and programmatic utilities for run welch statistics.

Examples
--------
Show all command-line parameters:

    python scripts/statistics/run_welch_statistics.py --help

Representative execution:

    python scripts/statistics/run_welch_statistics.py \
        --dataset 2d_time \
        --source-mode filtered_unet \
        --project-root . \
        --input-root results/img/2d_time
"""

from __future__ import annotations

"""Welch-test analysis for the PFT quantitative fluorescence pipeline.

The script uses independent image/ROI summaries generated by
``create_statistics_graphs.py`` in full mode. Individual cells are never treated
as independent observations. It performs:

* planned two-sided Welch tests for all eligible scalar ROI metrics;
* exploratory all-pairwise scalar comparisons in a separate output;
* pointwise Welch tests for axial and radial ROI profiles;
* multiplicity correction using Holm, Bonferroni, or Benjamini-Hochberg FDR;
* 95% confidence intervals and Hedges' g effect sizes;
* extraction of contiguous significant profile intervals;
* CSV, XLSX, and JSON outputs.

Example-mode outputs are rejected because one image per condition is not
sufficient for inferential statistics.
"""

import argparse
import csv
import json
import math
import re
import shutil
import sys
from dataclasses import dataclass
from itertools import combinations
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
from openpyxl import Workbook
from openpyxl.formatting.rule import CellIsRule
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from scipy.stats import t as student_t

SCRIPT_FILE = Path(__file__).resolve()
EPS = np.finfo(np.float64).eps
DATASETS = ("2d_time", "2d_wga_dapi", "3d_mip")
DEFAULT_SOURCE_MODES = {
    "2d_time": "filtered_unet",
    "2d_wga_dapi": "filtered_unet",
    "3d_mip": "deconv_masked",
}
CHANNELS = {
    "2d_time": ("HADA",),
    "2d_wga_dapi": ("DAPI", "WGA"),
    "3d_mip": ("HADA", "NADA", "TADA"),
}
CONDITION_ORDER = {
    "2d_time": (
        "THY_5min",
        "NHS_5min",
        "THY_20min",
        "NHS_20min",
        "THY_40min",
        "NHS_40min",
        "THY_120min",
        "NHS_120min",
    ),
    "2d_wga_dapi": ("THY_noCSP", "THY_CSP", "NHS_noCSP", "NHS_CSP"),
    "3d_mip": ("THY", "NHS"),
}
NON_METRIC_COLUMNS = {
    "dataset",
    "annotation_id",
    "sample_name",
    "condition",
    "medium",
    "time_min",
    "csp",
    "source_label",
    "pixel_size_um",
}


@dataclass(frozen=True)
class Comparison:
    """Store validated configuration or result data for comparison."""
    name: str
    family: str
    group_a_label: str
    group_a_conditions: tuple[str, ...]
    group_b_label: str
    group_b_conditions: tuple[str, ...]
    role: str


@dataclass(frozen=True)
class WelchResult:
    """Store validated configuration or result data for welch result."""
    n_a: int
    n_b: int
    mean_a: float
    sd_a: float
    mean_b: float
    sd_b: float
    difference_b_minus_a: float
    standard_error: float
    t_statistic: float
    degrees_of_freedom: float
    ci95_low: float
    ci95_high: float
    p_raw: float
    hedges_g: float
    status: str


def find_project_root(explicit: Path | None = None) -> Path:
    """Find project root in the available data or project structure.

    Args:
        explicit (Path | None): Filesystem path used for explicit. ``None`` selects the function's default behavior.

    Returns:
        Path: Resolved or generated filesystem path.

    Raises:
        FileNotFoundError: If the supplied inputs or runtime state violate the function's requirements.
        RuntimeError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = find_project_root()
    """
    if explicit is not None:
        root = explicit.expanduser().resolve()
        if not (root / "scripts").is_dir():
            raise FileNotFoundError(f"Project root does not contain scripts/: {root}")
        return root
    search_start = SCRIPT_FILE.parent.resolve()
    for candidate in (search_start, *search_start.parents):
        if (candidate / "scripts").is_dir() and (candidate / "src" / "PFT").is_dir():
            return candidate
    raise RuntimeError("Cannot locate the PFT project root; provide --project-root.")


def read_csv(path: Path) -> list[dict[str, str]]:
    """Read CSV data from persistent storage.

    Args:
        path (Path): Filesystem path to the required input or output resource.

    Returns:
        list[dict[str, str]]: Mapping containing the generated or resolved values.

    Example:
        >>> result = read_csv(path=Path("path/to/resource"))
    """
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def write_csv(path: Path, rows: Sequence[dict[str, object]]) -> None:
    """Write CSV data to persistent storage.

    Args:
        path (Path): Filesystem path to the required input or output resource.
        rows (Sequence[dict[str, object]]): Text value specifying rows.

    Example:
        >>> write_csv(path=Path("path/to/resource"), rows="rows")
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def safe_float(value: object, default: float = math.nan) -> float:
    """Return safe float for the supplied inputs.

    Args:
        value (object): Value to validate, transform, store, or forward.
        default (float): Numerical value controlling default. Defaults to ``math.nan``.

    Returns:
        float: Computed numerical result.

    Example:
        >>> result = safe_float(value=...)
    """
    try:
        number = float(value)
    except (TypeError, ValueError):
        return default
    return number if np.isfinite(number) else default


def numeric_metrics(rows: Sequence[dict[str, str]]) -> list[str]:
    """Return numeric metrics for the supplied inputs.

    Args:
        rows (Sequence[dict[str, str]]): Text value specifying rows.

    Returns:
        list[str]: Collection containing the generated or selected values.

    Example:
        >>> result = numeric_metrics(rows="rows")
    """
    metrics: list[str] = []
    for row in rows:
        for key, value in row.items():
            if key in NON_METRIC_COLUMNS or key in metrics:
                continue
            number = safe_float(value)
            if np.isfinite(number):
                metrics.append(key)
    return sorted(metrics)


def values_for_metric(
    rows: Sequence[dict[str, str]],
    metric: str,
    conditions: Sequence[str],
) -> np.ndarray:
    """Return values for metric for the supplied inputs.

    Args:
        rows (Sequence[dict[str, str]]): Text value specifying rows.
        metric (str): Text value specifying metric.
        conditions (Sequence[str]): Text value specifying conditions.

    Returns:
        np.ndarray: Array containing the processed result.

    Example:
        >>> result = values_for_metric(
        ...     rows="rows",
        ...     metric="metric",
        ...     conditions="conditions",
        ... )
    """
    selected = {
        condition for condition in conditions
    }
    values = np.asarray(
        [
            safe_float(row.get(metric))
            for row in rows
            if str(row.get("condition", "")) in selected
        ],
        dtype=np.float64,
    )
    return values[np.isfinite(values)]


def welch_test(a: np.ndarray, b: np.ndarray, min_group_n: int) -> WelchResult:
    """Return welch test for the supplied inputs.

    Args:
        a (np.ndarray): Array containing a.
        b (np.ndarray): Array containing b.
        min_group_n (int): Minimum permitted value of group n.

    Returns:
        WelchResult: Result produced by the operation.

    Example:
        >>> result = welch_test(
        ...     a=image_array,
        ...     b=image_array,
        ...     min_group_n=1,
        ... )
    """
    a = np.asarray(a, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    a = a[np.isfinite(a)]
    b = b[np.isfinite(b)]
    n_a = int(a.size)
    n_b = int(b.size)
    mean_a = float(np.mean(a)) if n_a else math.nan
    mean_b = float(np.mean(b)) if n_b else math.nan
    sd_a = float(np.std(a, ddof=1)) if n_a > 1 else math.nan
    sd_b = float(np.std(b, ddof=1)) if n_b > 1 else math.nan
    difference = mean_b - mean_a if n_a and n_b else math.nan

    if n_a < min_group_n or n_b < min_group_n:
        return WelchResult(
            n_a,
            n_b,
            mean_a,
            sd_a,
            mean_b,
            sd_b,
            difference,
            math.nan,
            math.nan,
            math.nan,
            math.nan,
            math.nan,
            math.nan,
            math.nan,
            "INSUFFICIENT_N",
        )

    variance_a = sd_a**2
    variance_b = sd_b**2
    term_a = variance_a / n_a
    term_b = variance_b / n_b
    standard_error = math.sqrt(term_a + term_b)
    if standard_error <= EPS:
        p_raw = 1.0 if abs(difference) <= EPS else 0.0
        t_statistic = 0.0 if abs(difference) <= EPS else math.copysign(math.inf, difference)
        df = math.inf
        ci_low = difference
        ci_high = difference
    else:
        t_statistic = difference / standard_error
        denominator = (term_a**2) / (n_a - 1) + (term_b**2) / (n_b - 1)
        df = ((term_a + term_b) ** 2) / denominator if denominator > EPS else math.inf
        p_raw = float(2.0 * student_t.sf(abs(t_statistic), df))
        critical = float(student_t.ppf(0.975, df))
        ci_low = difference - critical * standard_error
        ci_high = difference + critical * standard_error

    pooled_denominator = n_a + n_b - 2
    if pooled_denominator > 0:
        pooled_variance = (
            (n_a - 1) * variance_a + (n_b - 1) * variance_b
        ) / pooled_denominator
        pooled_sd = math.sqrt(max(pooled_variance, 0.0))
    else:
        pooled_sd = math.nan
    if np.isfinite(pooled_sd) and pooled_sd > EPS:
        cohen_d = difference / pooled_sd
        correction = 1.0 - 3.0 / (4.0 * (n_a + n_b) - 9.0)
        hedges_g = correction * cohen_d
    else:
        hedges_g = 0.0 if abs(difference) <= EPS else math.nan

    return WelchResult(
        n_a,
        n_b,
        mean_a,
        sd_a,
        mean_b,
        sd_b,
        difference,
        standard_error,
        t_statistic,
        df,
        ci_low,
        ci_high,
        p_raw,
        hedges_g,
        "OK",
    )


def adjust_pvalues(values: Sequence[float], method: str) -> list[float]:
    """Return adjust pvalues for the supplied inputs.

    Args:
        values (Sequence[float]): Numerical value controlling values.
        method (str): Text value specifying method.

    Returns:
        list[float]: Collection containing the generated or selected values.

    Raises:
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = adjust_pvalues(values=0.5, method="method")
    """
    p = np.asarray(values, dtype=np.float64)
    adjusted = np.full(p.shape, np.nan, dtype=np.float64)
    finite_indices = np.flatnonzero(np.isfinite(p))
    if finite_indices.size == 0:
        return adjusted.tolist()
    finite_p = p[finite_indices]
    m = int(finite_p.size)

    if method == "bonferroni":
        corrected = np.minimum(1.0, finite_p * m)
    elif method == "holm":
        order = np.argsort(finite_p)
        ordered = finite_p[order]
        ordered_adjusted = np.empty_like(ordered)
        running = 0.0
        for rank, value in enumerate(ordered):
            candidate = (m - rank) * value
            running = max(running, candidate)
            ordered_adjusted[rank] = min(1.0, running)
        corrected = np.empty_like(ordered_adjusted)
        corrected[order] = ordered_adjusted
    elif method == "fdr_bh":
        order = np.argsort(finite_p)
        ordered = finite_p[order]
        ordered_adjusted = np.empty_like(ordered)
        running = 1.0
        for reverse_rank in range(m - 1, -1, -1):
            rank = reverse_rank + 1
            candidate = ordered[reverse_rank] * m / rank
            running = min(running, candidate)
            ordered_adjusted[reverse_rank] = min(1.0, running)
        corrected = np.empty_like(ordered_adjusted)
        corrected[order] = ordered_adjusted
    else:
        raise ValueError(f"Unsupported correction method: {method}")

    adjusted[finite_indices] = corrected
    return adjusted.tolist()


def effect_size_magnitude(value: float) -> str:
    """Return effect size magnitude for the supplied inputs.

    Args:
        value (float): Value to validate, transform, store, or forward.

    Returns:
        str: Generated or resolved text value.

    Example:
        >>> result = effect_size_magnitude(value=0.5)
    """
    if not np.isfinite(value):
        return "not_available"
    absolute = abs(value)
    if absolute < 0.2:
        return "negligible"
    if absolute < 0.5:
        return "small"
    if absolute < 0.8:
        return "medium"
    return "large"


def metric_base_for_3d(metric: str) -> str:
    """Return metric base for three-dimensional data for the supplied inputs.

    Args:
        metric (str): Text value specifying metric.

    Returns:
        str: Generated or resolved text value.

    Example:
        >>> result = metric_base_for_3d(metric="metric")
    """
    for channel in CHANNELS["3d_mip"]:
        prefix = f"{channel.lower()}_"
        if metric.startswith(prefix):
            return metric[len(prefix):]
    return metric


def graph_target(dataset: str, metric: str) -> str:
    """Return graph target for the supplied inputs.

    Args:
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.
        metric (str): Text value specifying metric.

    Returns:
        str: Generated or resolved text value.

    Example:
        >>> result = graph_target(dataset="2d_time", metric="metric")
    """
    lower = metric.lower()
    if metric == "n_cells":
        return "detected_cells"
    if "length" in lower and "axial_extent" not in lower:
        return "cell_length"
    if "homogeneity" in lower:
        return "homogeneity"
    if lower.startswith("dapi_axial_extent"):
        return "dapi_axial_signal_length"
    if "wga_dapi" in lower or "manders" in lower or "overlap" in lower or "pearson" in lower:
        return "wga_dapi_spatial_relationship"
    if "axial_" in lower or any(
        token in lower
        for token in (
            "pole1_intensity",
            "pole2_intensity",
            "midcell_intensity",
            "mean_pole_intensity",
            "midcell_to_pole_ratio",
            "pole_asymmetry",
        )
    ):
        return "axial_profile_summary"
    if "radial_" in lower or "boundary_to_centre" in lower or "centre_intensity" in lower or "boundary_intensity" in lower:
        return "radial_profile_summary"
    if dataset == "3d_mip":
        return "3d_channel_metric"
    return "scalar_metric"


def planned_comparisons(dataset: str) -> list[Comparison]:
    """Return planned comparisons for the supplied inputs.

    Args:
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.

    Returns:
        list[Comparison]: Collection containing the generated or selected values.

    Raises:
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = planned_comparisons(dataset="2d_time")
    """
    if dataset == "2d_time":
        return [
            Comparison(
                name=f"THY vs NHS at {time} min",
                family="THY_vs_NHS_across_time",
                group_a_label=f"THY {time} min",
                group_a_conditions=(f"THY_{time}min",),
                group_b_label=f"NHS {time} min",
                group_b_conditions=(f"NHS_{time}min",),
                role="primary",
            )
            for time in (5, 20, 40, 120)
        ]
    if dataset == "2d_wga_dapi":
        return [
            Comparison(
                "THY vs THY + CSP",
                "primary_csp",
                "THY",
                ("THY_noCSP",),
                "THY + CSP",
                ("THY_CSP",),
                "primary",
            ),
            Comparison(
                "NHS vs NHS + CSP",
                "primary_csp",
                "NHS",
                ("NHS_noCSP",),
                "NHS + CSP",
                ("NHS_CSP",),
                "primary",
            ),
            Comparison(
                "THY vs NHS without CSP",
                "secondary_medium",
                "THY",
                ("THY_noCSP",),
                "NHS",
                ("NHS_noCSP",),
                "secondary",
            ),
            Comparison(
                "THY + CSP vs NHS + CSP",
                "secondary_medium",
                "THY + CSP",
                ("THY_CSP",),
                "NHS + CSP",
                ("NHS_CSP",),
                "secondary",
            ),
            Comparison(
                "All THY vs all NHS",
                "exploratory_pooled_medium",
                "All THY",
                ("THY_noCSP", "THY_CSP"),
                "All NHS",
                ("NHS_noCSP", "NHS_CSP"),
                "exploratory",
            ),
        ]
    if dataset == "3d_mip":
        return [
            Comparison(
                "THY vs NHS",
                "THY_vs_NHS_across_channels",
                "THY",
                ("THY",),
                "NHS",
                ("NHS",),
                "primary",
            )
        ]
    raise ValueError(f"Unsupported dataset: {dataset}")


def all_pairwise_comparisons(dataset: str, conditions_present: Sequence[str]) -> list[Comparison]:
    """Return all pairwise comparisons for the supplied inputs.

    Args:
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.
        conditions_present (Sequence[str]): Text value specifying conditions present.

    Returns:
        list[Comparison]: Collection containing the generated or selected values.

    Example:
        >>> result = all_pairwise_comparisons(dataset="2d_time", conditions_present="conditions_present")
    """
    order = [condition for condition in CONDITION_ORDER[dataset] if condition in conditions_present]
    return [
        Comparison(
            name=f"{a} vs {b}",
            family="all_pairwise_conditions",
            group_a_label=a,
            group_a_conditions=(a,),
            group_b_label=b,
            group_b_conditions=(b,),
            role="exploratory_all_pairwise",
        )
        for a, b in combinations(order, 2)
    ]


def scalar_family_id(dataset: str, metric: str, comparison: Comparison, all_pairwise: bool) -> str:
    """Return scalar family id for the supplied inputs.

    Args:
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.
        metric (str): Text value specifying metric.
        comparison (Comparison): Value specifying comparison for the operation.
        all_pairwise (bool): Boolean flag controlling all pairwise.

    Returns:
        str: Generated or resolved text value.

    Example:
        >>> result = scalar_family_id(
        ...     dataset="2d_time",
        ...     metric="metric",
        ...     comparison=...,
        ...     all_pairwise=True,
        ... )
    """
    if all_pairwise:
        return f"all_pairwise::{metric}"
    if dataset == "3d_mip":
        return f"{comparison.family}::{metric_base_for_3d(metric)}"
    return f"{comparison.family}::{metric}"


def result_to_row(
    *,
    dataset: str,
    metric: str,
    comparison: Comparison,
    result: WelchResult,
    family_id: str,
    correction: str,
    alpha: float,
) -> dict[str, object]:
    """Return result to row for the supplied inputs.

    Args:
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.
        metric (str): Text value specifying metric.
        comparison (Comparison): Value specifying comparison for the operation.
        result (WelchResult): Value specifying result for the operation.
        family_id (str): Text value specifying family id.
        correction (str): Text value specifying correction.
        alpha (float): Opacity coefficient used when blending image layers.

    Returns:
        dict[str, object]: Mapping containing the generated or resolved values.

    Example:
        >>> result = result_to_row(
        ...     dataset="2d_time",
        ...     metric="metric",
        ...     comparison=...,
        ...     result=...,
        ...     family_id="family_id",
        ...     correction="correction",
        ...     alpha=0.5,
        ... )
    """
    percentage_difference = (
        100.0 * result.difference_b_minus_a / abs(result.mean_a)
        if np.isfinite(result.mean_a) and abs(result.mean_a) > EPS
        else math.nan
    )
    return {
        "dataset": dataset,
        "metric": metric,
        "graph_target": graph_target(dataset, metric),
        "comparison": comparison.name,
        "comparison_role": comparison.role,
        "correction_family": family_id,
        "group_a": comparison.group_a_label,
        "group_a_conditions": ";".join(comparison.group_a_conditions),
        "group_b": comparison.group_b_label,
        "group_b_conditions": ";".join(comparison.group_b_conditions),
        "n_a_rois": result.n_a,
        "n_b_rois": result.n_b,
        "mean_a": result.mean_a,
        "sd_a": result.sd_a,
        "mean_b": result.mean_b,
        "sd_b": result.sd_b,
        "difference_b_minus_a": result.difference_b_minus_a,
        "percentage_difference_relative_to_a": percentage_difference,
        "standard_error": result.standard_error,
        "ci95_low": result.ci95_low,
        "ci95_high": result.ci95_high,
        "welch_t": result.t_statistic,
        "welch_df": result.degrees_of_freedom,
        "p_raw": result.p_raw,
        "p_adjusted": math.nan,
        "correction_method": correction,
        "alpha": alpha,
        "significant_after_correction": False,
        "hedges_g": result.hedges_g,
        "effect_size_magnitude": effect_size_magnitude(result.hedges_g),
        "status": result.status,
    }


def apply_family_correction(
    rows: list[dict[str, object]],
    correction: str,
    alpha: float,
) -> None:
    """Apply the configured operation to family correction.

    Args:
        rows (list[dict[str, object]]): Text value specifying rows.
        correction (str): Text value specifying correction.
        alpha (float): Opacity coefficient used when blending image layers.

    Example:
        >>> apply_family_correction(
        ...     rows="rows",
        ...     correction="correction",
        ...     alpha=0.5,
        ... )
    """
    families: dict[str, list[int]] = {}
    for index, row in enumerate(rows):
        if row.get("status") != "OK":
            continue
        families.setdefault(str(row["correction_family"]), []).append(index)
    for indices in families.values():
        adjusted = adjust_pvalues(
            [safe_float(rows[index].get("p_raw")) for index in indices], correction
        )
        for index, p_adjusted in zip(indices, adjusted):
            rows[index]["p_adjusted"] = p_adjusted
            rows[index]["significant_after_correction"] = bool(
                np.isfinite(p_adjusted) and p_adjusted < alpha
            )


def calculate_scalar_tests(
    dataset: str,
    rows: list[dict[str, str]],
    comparisons: Sequence[Comparison],
    correction: str,
    alpha: float,
    min_group_n: int,
    all_pairwise: bool,
) -> list[dict[str, object]]:
    """Calculate scalar tests from the supplied data.

    Args:
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.
        rows (list[dict[str, str]]): Text value specifying rows.
        comparisons (Sequence[Comparison]): Value specifying comparisons for the operation.
        correction (str): Text value specifying correction.
        alpha (float): Opacity coefficient used when blending image layers.
        min_group_n (int): Minimum permitted value of group n.
        all_pairwise (bool): Boolean flag controlling all pairwise.

    Returns:
        list[dict[str, object]]: Mapping containing the generated or resolved values.

    Example:
        >>> result = calculate_scalar_tests(
        ...     dataset="2d_time",
        ...     rows="rows",
        ...     comparisons=[],
        ...     correction="correction",
        ...     alpha=0.5,
        ...     min_group_n=1,
        ...     all_pairwise=True,
        ... )
    """
    metrics = numeric_metrics(rows)
    output: list[dict[str, object]] = []
    for metric in metrics:
        for comparison in comparisons:
            a = values_for_metric(rows, metric, comparison.group_a_conditions)
            b = values_for_metric(rows, metric, comparison.group_b_conditions)
            result = welch_test(a, b, min_group_n)
            family_id = scalar_family_id(dataset, metric, comparison, all_pairwise)
            output.append(
                result_to_row(
                    dataset=dataset,
                    metric=metric,
                    comparison=comparison,
                    result=result,
                    family_id=family_id,
                    correction=correction,
                    alpha=alpha,
                )
            )
    apply_family_correction(output, correction, alpha)
    return output


def read_roi_profiles(path: Path) -> dict[tuple[str, str, str], list[np.ndarray]]:
    """Read region of interest profiles from persistent storage.

    Args:
        path (Path): Filesystem path to the required input or output resource.

    Returns:
        dict[tuple[str, str, str], list[np.ndarray]]: Mapping containing the generated or resolved values.

    Example:
        >>> result = read_roi_profiles(path=Path("path/to/resource"))
    """
    store: dict[tuple[str, str, str], list[np.ndarray]] = {}
    with np.load(path) as archive:
        for key in archive.files:
            parts = key.split("|")
            if len(parts) < 4:
                continue
            condition, channel, _roi_identifier, profile_type = parts[0], parts[1], parts[2], parts[-1]
            if profile_type not in {"axial", "radial"}:
                continue
            profile = np.asarray(archive[key], dtype=np.float64)
            store.setdefault((condition, channel, profile_type), []).append(profile)
    return store


def collect_profiles(
    store: dict[tuple[str, str, str], list[np.ndarray]],
    conditions: Sequence[str],
    channel: str,
    profile_type: str,
) -> list[np.ndarray]:
    """Collect profiles from the available inputs.

    Args:
        store (dict[tuple[str, str, str], list[np.ndarray]]): Array containing store.
        conditions (Sequence[str]): Text value specifying conditions.
        channel (str): Channel index or channel identifier selected for processing.
        profile_type (str): Text value specifying profile type.

    Returns:
        list[np.ndarray]: Collection containing the generated or selected values.

    Example:
        >>> result = collect_profiles(
        ...     store=image_array,
        ...     conditions="conditions",
        ...     channel="channel",
        ...     profile_type="profile_type",
        ... )
    """
    profiles: list[np.ndarray] = []
    for condition in conditions:
        profiles.extend(store.get((condition, channel, profile_type), []))
    return profiles


def calculate_pointwise_profile_tests(
    dataset: str,
    store: dict[tuple[str, str, str], list[np.ndarray]],
    comparisons: Sequence[Comparison],
    profile_type: str,
    correction: str,
    alpha: float,
    min_group_n: int,
) -> list[dict[str, object]]:
    """Calculate pointwise profile tests from the supplied data.

    Args:
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.
        store (dict[tuple[str, str, str], list[np.ndarray]]): Array containing store.
        comparisons (Sequence[Comparison]): Value specifying comparisons for the operation.
        profile_type (str): Text value specifying profile type.
        correction (str): Text value specifying correction.
        alpha (float): Opacity coefficient used when blending image layers.
        min_group_n (int): Minimum permitted value of group n.

    Returns:
        list[dict[str, object]]: Mapping containing the generated or resolved values.

    Raises:
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = calculate_pointwise_profile_tests(
        ...     dataset="2d_time",
        ...     store=image_array,
        ...     comparisons=[],
        ...     profile_type="profile_type",
        ...     correction="correction",
        ...     alpha=0.5,
        ...     min_group_n=1,
        ... )
    """
    output: list[dict[str, object]] = []
    for comparison in comparisons:
        for channel in CHANNELS[dataset]:
            profiles_a = collect_profiles(
                store, comparison.group_a_conditions, channel, profile_type
            )
            profiles_b = collect_profiles(
                store, comparison.group_b_conditions, channel, profile_type
            )
            if not profiles_a and not profiles_b:
                continue
            lengths = {profile.size for profile in (*profiles_a, *profiles_b)}
            if len(lengths) != 1:
                raise ValueError(
                    f"Profile lengths differ for {dataset}, {comparison.name}, "
                    f"{channel}, {profile_type}: {sorted(lengths)}"
                )
            profile_length = next(iter(lengths))
            matrix_a = (
                np.vstack(profiles_a)
                if profiles_a
                else np.empty((0, profile_length), dtype=np.float64)
            )
            matrix_b = (
                np.vstack(profiles_b)
                if profiles_b
                else np.empty((0, profile_length), dtype=np.float64)
            )
            family_id = (
                f"{dataset}::{comparison.name}::{channel}::{profile_type}::coordinates"
            )
            family_rows: list[dict[str, object]] = []
            for bin_index in range(profile_length):
                result = welch_test(
                    matrix_a[:, bin_index], matrix_b[:, bin_index], min_group_n
                )
                coordinate = (
                    bin_index / (profile_length - 1)
                    if profile_length > 1
                    else 0.0
                )
                family_rows.append(
                    {
                        "dataset": dataset,
                        "profile_type": profile_type,
                        "channel": channel,
                        "comparison": comparison.name,
                        "comparison_role": comparison.role,
                        "correction_family": family_id,
                        "group_a": comparison.group_a_label,
                        "group_b": comparison.group_b_label,
                        "coordinate_index": bin_index,
                        "normalized_coordinate": coordinate,
                        "n_a_rois": result.n_a,
                        "n_b_rois": result.n_b,
                        "mean_a": result.mean_a,
                        "sd_a": result.sd_a,
                        "mean_b": result.mean_b,
                        "sd_b": result.sd_b,
                        "difference_b_minus_a": result.difference_b_minus_a,
                        "standard_error": result.standard_error,
                        "ci95_low": result.ci95_low,
                        "ci95_high": result.ci95_high,
                        "welch_t": result.t_statistic,
                        "welch_df": result.degrees_of_freedom,
                        "p_raw": result.p_raw,
                        "p_adjusted": math.nan,
                        "correction_method": correction,
                        "alpha": alpha,
                        "significant_after_correction": False,
                        "hedges_g": result.hedges_g,
                        "effect_size_magnitude": effect_size_magnitude(result.hedges_g),
                        "status": result.status,
                    }
                )
            valid_indices = [
                index for index, row in enumerate(family_rows) if row["status"] == "OK"
            ]
            adjusted = adjust_pvalues(
                [safe_float(family_rows[index]["p_raw"]) for index in valid_indices],
                correction,
            )
            for index, p_adjusted in zip(valid_indices, adjusted):
                family_rows[index]["p_adjusted"] = p_adjusted
                family_rows[index]["significant_after_correction"] = bool(
                    np.isfinite(p_adjusted) and p_adjusted < alpha
                )
            output.extend(family_rows)
    return output


def significant_intervals(
    pointwise_rows: Sequence[dict[str, object]],
) -> list[dict[str, object]]:
    """Return significant intervals for the supplied inputs.

    Args:
        pointwise_rows (Sequence[dict[str, object]]): Text value specifying pointwise rows.

    Returns:
        list[dict[str, object]]: Mapping containing the generated or resolved values.

    Example:
        >>> result = significant_intervals(pointwise_rows="pointwise_rows")
    """
    grouped: dict[tuple[str, str, str, str], list[dict[str, object]]] = {}
    for row in pointwise_rows:
        if not bool(row.get("significant_after_correction", False)):
            continue
        key = (
            str(row.get("dataset", "")),
            str(row.get("profile_type", "")),
            str(row.get("channel", "")),
            str(row.get("comparison", "")),
        )
        grouped.setdefault(key, []).append(dict(row))

    intervals: list[dict[str, object]] = []
    for key, rows in grouped.items():
        rows.sort(key=lambda row: int(row["coordinate_index"]))
        current: list[dict[str, object]] = []
        previous_index: int | None = None
        previous_direction: str | None = None
        for row in rows:
            index = int(row["coordinate_index"])
            difference = safe_float(row.get("difference_b_minus_a"), 0.0)
            direction = "B > A" if difference > 0 else "A > B" if difference < 0 else "equal"
            if (
                current
                and previous_index is not None
                and (index != previous_index + 1 or direction != previous_direction)
            ):
                intervals.append(_interval_row(key, current, previous_direction or ""))
                current = []
            current.append(row)
            previous_index = index
            previous_direction = direction
        if current:
            intervals.append(_interval_row(key, current, previous_direction or ""))
    return intervals


def _interval_row(
    key: tuple[str, str, str, str],
    rows: Sequence[dict[str, object]],
    direction: str,
) -> dict[str, object]:
    """Return interval row for the supplied inputs.

    Args:
        key (tuple[str, str, str, str]): Key used to access or identify an entry in a mapping.
        rows (Sequence[dict[str, object]]): Text value specifying rows.
        direction (str): Text value specifying direction.

    Returns:
        dict[str, object]: Mapping containing the generated or resolved values.

    Example:
        >>> result = _interval_row(
        ...     key="key",
        ...     rows="rows",
        ...     direction="direction",
        ... )
    """
    dataset, profile_type, channel, comparison = key
    differences = np.asarray(
        [safe_float(row.get("difference_b_minus_a")) for row in rows], dtype=float
    )
    adjusted = np.asarray(
        [safe_float(row.get("p_adjusted")) for row in rows], dtype=float
    )
    first = rows[0]
    last = rows[-1]
    return {
        "dataset": dataset,
        "profile_type": profile_type,
        "channel": channel,
        "comparison": comparison,
        "group_a": first.get("group_a", ""),
        "group_b": first.get("group_b", ""),
        "start_bin": int(first["coordinate_index"]),
        "end_bin": int(last["coordinate_index"]),
        "start_coordinate": safe_float(first.get("normalized_coordinate")),
        "end_coordinate": safe_float(last.get("normalized_coordinate")),
        "n_consecutive_bins": len(rows),
        "direction": direction,
        "mean_difference_b_minus_a": float(np.nanmean(differences)),
        "minimum_adjusted_p": float(np.nanmin(adjusted)),
    }


def _excel_value(value: object) -> object:
    """Return excel value for the supplied inputs.

    Args:
        value (object): Value to validate, transform, store, or forward.

    Returns:
        object: Result produced by the operation.

    Example:
        >>> result = _excel_value(value=...)
    """
    if isinstance(value, (np.floating, np.integer, np.bool_)):
        value = value.item()
    if isinstance(value, float) and not np.isfinite(value):
        return None
    return value


def add_sheet_from_rows(workbook: Workbook, title: str, rows: Sequence[dict[str, object]]) -> None:
    """Add sheet from rows to the current data structure.

    Args:
        workbook (Workbook): Value specifying workbook for the operation.
        title (str): Title displayed on the generated figure or report section.
        rows (Sequence[dict[str, object]]): Text value specifying rows.

    Example:
        >>> add_sheet_from_rows(
        ...     workbook=...,
        ...     title="title",
        ...     rows="rows",
        ... )
    """
    sheet = workbook.create_sheet(title=title[:31])
    if not rows:
        sheet.append(["No results"])
        return
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    sheet.append(fields)
    for row in rows:
        sheet.append([_excel_value(row.get(field)) for field in fields])

    header_fill = PatternFill("solid", fgColor="1F4E78")
    for cell in sheet[1]:
        cell.fill = header_fill
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = sheet.dimensions

    p_adjusted_col = fields.index("p_adjusted") + 1 if "p_adjusted" in fields else None
    if p_adjusted_col is not None and sheet.max_row >= 2:
        column_letter = get_column_letter(p_adjusted_col)
        sheet.conditional_formatting.add(
            f"{column_letter}2:{column_letter}{sheet.max_row}",
            CellIsRule(
                operator="lessThan",
                formula=["0.05"],
                fill=PatternFill("solid", fgColor="C6EFCE"),
            ),
        )

    for column_index, field in enumerate(fields, start=1):
        max_length = len(field)
        for cell in sheet[get_column_letter(column_index)]:
            value = "" if cell.value is None else str(cell.value)
            max_length = max(max_length, len(value))
        sheet.column_dimensions[get_column_letter(column_index)].width = min(max(max_length + 2, 11), 36)

    for row in sheet.iter_rows(min_row=2):
        for cell in row:
            if isinstance(cell.value, float):
                cell.number_format = "0.000000"


def write_workbook(
    path: Path,
    scalar_planned: Sequence[dict[str, object]],
    scalar_all_pairs: Sequence[dict[str, object]],
    axial_rows: Sequence[dict[str, object]],
    radial_rows: Sequence[dict[str, object]],
    intervals: Sequence[dict[str, object]],
    notes: Sequence[dict[str, object]],
) -> None:
    """Write workbook to persistent storage.

    Args:
        path (Path): Filesystem path to the required input or output resource.
        scalar_planned (Sequence[dict[str, object]]): Text value specifying scalar planned.
        scalar_all_pairs (Sequence[dict[str, object]]): Text value specifying scalar all pairs.
        axial_rows (Sequence[dict[str, object]]): Text value specifying axial rows.
        radial_rows (Sequence[dict[str, object]]): Text value specifying radial rows.
        intervals (Sequence[dict[str, object]]): Text value specifying intervals.
        notes (Sequence[dict[str, object]]): Text value specifying notes.

    Example:
        >>> write_workbook(
        ...     path=Path("path/to/resource"),
        ...     scalar_planned="scalar_planned",
        ...     scalar_all_pairs="scalar_all_pairs",
        ...     axial_rows="axial_rows",
        ...     radial_rows="radial_rows",
        ...     intervals="intervals",
        ...     notes="notes",
        ... )
    """
    workbook = Workbook()
    workbook.remove(workbook.active)
    add_sheet_from_rows(workbook, "scalar_planned", scalar_planned)
    add_sheet_from_rows(workbook, "scalar_all_pairs", scalar_all_pairs)
    add_sheet_from_rows(workbook, "axial_pointwise", axial_rows)
    add_sheet_from_rows(workbook, "radial_pointwise", radial_rows)
    add_sheet_from_rows(workbook, "significant_intervals", intervals)
    add_sheet_from_rows(workbook, "notes", notes)
    path.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(path)


def validate_full_mode_input(input_root: Path) -> dict[str, object]:
    """Validate full mode input against the required constraints.

    Args:
        input_root (Path): Directory used for input.

    Returns:
        dict[str, object]: Mapping containing the generated or resolved values.

    Raises:
        FileNotFoundError: If the supplied inputs or runtime state violate the function's requirements.
        RuntimeError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = validate_full_mode_input(input_root=Path("path/to/resource"))
    """
    summary_path = input_root / "graph_run_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"Missing graph_run_summary.json: {summary_path}. Run full graph generation first."
        )
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    if summary.get("run_mode") != "full":
        raise RuntimeError(
            f"Inferential testing requires full-mode ROI outputs, but {input_root} "
            f"reports run_mode={summary.get('run_mode')!r}. Remove --example and process all images first."
        )
    if str(input_root).lower().find("graphs_example") >= 0:
        raise RuntimeError("Example graph outputs cannot be used for Welch tests.")
    return summary


def prepare_output(path: Path, overwrite: bool) -> None:
    """Prepare output for downstream processing.

    Args:
        path (Path): Filesystem path to the required input or output resource.
        overwrite (bool): Whether an existing output may be replaced.

    Raises:
        FileExistsError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> prepare_output(path=Path("path/to/resource"), overwrite=True)
    """
    if path.exists() and any(path.iterdir()):
        if not overwrite:
            raise FileExistsError(f"Output directory is not empty: {path}. Use --overwrite.")
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def process_dataset(
    *,
    project_root: Path,
    dataset: str,
    source_mode: str,
    input_root: Path,
    output_root: Path,
    scalar_correction: str,
    profile_correction: str,
    alpha: float,
    min_group_n: int,
    overwrite: bool,
) -> dict[str, object]:
    """Process dataset using the configured workflow.

    Args:
        project_root (Path): Root directory of the PFT project containing the results, models, scripts, and source-code directories.
        dataset (str): Dataset identifier that selects the supported acquisition and processing workflow, for example ``"2d_time"`` or ``"3d_data"``.
        source_mode (str): Preprocessing source used to construct the input, such as the original image, a filtered image, or a U-Net-masked image.
        input_root (Path): Directory used for input.
        output_root (Path): Directory used for output.
        scalar_correction (str): Text value specifying scalar correction.
        profile_correction (str): Text value specifying profile correction.
        alpha (float): Opacity coefficient used when blending image layers.
        min_group_n (int): Minimum permitted value of group n.
        overwrite (bool): Whether an existing output may be replaced.

    Returns:
        dict[str, object]: Mapping containing the generated or resolved values.

    Raises:
        FileNotFoundError: If the supplied inputs or runtime state violate the function's requirements.
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> result = process_dataset(
        ...     project_root=Path("path/to/resource"),
        ...     dataset="2d_time",
        ...     source_mode="original",
        ...     input_root=Path("path/to/resource"),
        ...     output_root=Path("path/to/resource"),
        ...     scalar_correction="scalar_correction",
        ...     profile_correction="profile_correction",
        ...     alpha=0.5,
        ...     min_group_n=1,
        ...     overwrite=True,
        ... )
    """
    summary = validate_full_mode_input(input_root)
    roi_summary_path = input_root / "roi_summary.csv"
    roi_profiles_path = input_root / "roi_profiles.npz"
    if not roi_summary_path.exists():
        raise FileNotFoundError(f"Missing ROI summary: {roi_summary_path}")
    if not roi_profiles_path.exists():
        raise FileNotFoundError(f"Missing ROI profiles: {roi_profiles_path}")

    prepare_output(output_root, overwrite)
    roi_rows = read_csv(roi_summary_path)
    if not roi_rows:
        raise ValueError(f"ROI summary is empty: {roi_summary_path}")
    conditions_present = sorted({str(row.get("condition", "")) for row in roi_rows})
    planned = planned_comparisons(dataset)
    pairwise = all_pairwise_comparisons(dataset, conditions_present)

    scalar_planned = calculate_scalar_tests(
        dataset,
        roi_rows,
        planned,
        scalar_correction,
        alpha,
        min_group_n,
        all_pairwise=False,
    )
    scalar_all_pairs = calculate_scalar_tests(
        dataset,
        roi_rows,
        pairwise,
        scalar_correction,
        alpha,
        min_group_n,
        all_pairwise=True,
    )

    profiles = read_roi_profiles(roi_profiles_path)
    axial_rows = calculate_pointwise_profile_tests(
        dataset,
        profiles,
        planned,
        "axial",
        profile_correction,
        alpha,
        min_group_n,
    )
    radial_rows = calculate_pointwise_profile_tests(
        dataset,
        profiles,
        planned,
        "radial",
        profile_correction,
        alpha,
        min_group_n,
    )
    intervals = significant_intervals([*axial_rows, *radial_rows])

    write_csv(output_root / "welch_scalar_planned.csv", scalar_planned)
    write_csv(output_root / "welch_scalar_all_pairwise.csv", scalar_all_pairs)
    write_csv(output_root / "welch_axial_pointwise.csv", axial_rows)
    write_csv(output_root / "welch_radial_pointwise.csv", radial_rows)
    write_csv(output_root / "welch_significant_profile_intervals.csv", intervals)

    notes = [
        {"item": "independent_observation", "value": "one image/ROI summary"},
        {"item": "test", "value": "two-sided Welch independent-samples t-test"},
        {"item": "difference_direction", "value": "mean(group B) - mean(group A)"},
        {"item": "confidence_interval", "value": "95% Welch confidence interval for the mean difference"},
        {"item": "effect_size", "value": "Hedges' g using pooled SD with small-sample correction"},
        {"item": "scalar_multiplicity_correction", "value": scalar_correction},
        {"item": "profile_multiplicity_correction", "value": profile_correction},
        {"item": "alpha", "value": alpha},
        {"item": "minimum_group_n", "value": min_group_n},
        {
            "item": "profile_inference",
            "value": "pointwise tests are exploratory and corrected across coordinates within each comparison/channel/profile family",
        },
        {
            "item": "example_mode",
            "value": "rejected because one image per condition is insufficient for inferential testing",
        },
        {
            "item": "3d_channel_comparisons",
            "value": "THY versus NHS is tested separately per channel; channel-versus-channel comparisons require paired analysis and are not tested here",
        },
    ]
    write_workbook(
        output_root / "welch_statistics.xlsx",
        scalar_planned,
        scalar_all_pairs,
        axial_rows,
        radial_rows,
        intervals,
        notes,
    )

    valid_scalar = [row for row in scalar_planned if row.get("status") == "OK"]
    significant_scalar = [
        row for row in valid_scalar if bool(row.get("significant_after_correction", False))
    ]
    valid_profile = [
        row for row in (*axial_rows, *radial_rows) if row.get("status") == "OK"
    ]
    significant_profile = [
        row
        for row in valid_profile
        if bool(row.get("significant_after_correction", False))
    ]
    analysis_summary = {
        "dataset": dataset,
        "source_mode": source_mode,
        "input_root": str(input_root),
        "output_root": str(output_root),
        "input_run_mode": summary.get("run_mode"),
        "n_roi_rows": len(roi_rows),
        "conditions_present": conditions_present,
        "scalar_correction_method": scalar_correction,
        "profile_correction_method": profile_correction,
        "alpha": alpha,
        "minimum_group_n": min_group_n,
        "n_planned_scalar_tests_valid": len(valid_scalar),
        "n_planned_scalar_tests_significant": len(significant_scalar),
        "n_pointwise_profile_tests_valid": len(valid_profile),
        "n_pointwise_profile_bins_significant": len(significant_profile),
        "n_significant_profile_intervals": len(intervals),
        "statistical_unit": "independent image/ROI",
        "warning": (
            "A statistically significant result does not establish biological importance. "
            "Interpret adjusted p-values together with confidence intervals, Hedges' g, "
            "effect direction, and the number of independent ROIs."
        ),
    }
    (output_root / "welch_statistics_summary.json").write_text(
        json.dumps(analysis_summary, indent=2), encoding="utf-8"
    )
    print(
        f"[WELCH] {dataset}: {len(valid_scalar)} valid planned scalar tests, "
        f"{len(significant_scalar)} significant after {scalar_correction}; "
        f"{len(intervals)} significant profile intervals"
    )
    print(f"Results: {output_root}")
    return analysis_summary


def build_parser() -> argparse.ArgumentParser:
    """Build parser from the supplied inputs.

    Returns:
        argparse.ArgumentParser: Result produced by the operation.

    Example:
        >>> result = build_parser()
    """
    parser = argparse.ArgumentParser(
        description=(
            "Run ROI-level Welch tests for PFT scalar metrics and axial/radial profiles. "
            "The script rejects example-mode data."
        )
    )
    parser.add_argument("--project-root", type=Path)
    parser.add_argument("--dataset", choices=("all", *DATASETS), default="all")
    parser.add_argument(
        "--source-mode",
        help="Custom source mode; valid only when one concrete dataset is selected.",
    )
    parser.add_argument(
        "--input-root",
        type=Path,
        help="Explicit full-mode graph directory; valid only for one dataset.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        help="Explicit statistics output directory; for --dataset all, dataset/source-mode subfolders are added.",
    )
    parser.add_argument(
        "--scalar-correction",
        choices=("holm", "bonferroni", "fdr_bh"),
        default="holm",
        help="Multiplicity correction for scalar metric families.",
    )
    parser.add_argument(
        "--profile-correction",
        choices=("holm", "bonferroni", "fdr_bh"),
        default="fdr_bh",
        help="Multiplicity correction across coordinates of each profile comparison.",
    )
    parser.add_argument("--alpha", type=float, default=0.05)
    parser.add_argument("--min-group-n", type=int, default=2)
    parser.add_argument("--skip-missing", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Execute the command-line workflow and return its process exit status.

    Args:
        argv (Sequence[str] | None): Optional command-line argument sequence. When omitted, arguments are read from ``sys.argv``. ``None`` selects the function's default behavior.

    Returns:
        int: Computed numerical result.

    Raises:
        FileNotFoundError: If the supplied inputs or runtime state violate the function's requirements.
        RuntimeError: If the supplied inputs or runtime state violate the function's requirements.
        ValueError: If the supplied inputs or runtime state violate the function's requirements.

    Example:
        >>> exit_code = main()
    """
    args = build_parser().parse_args(argv)
    if not 0.0 < args.alpha < 1.0:
        raise ValueError("--alpha must be between 0 and 1")
    if args.min_group_n < 2:
        raise ValueError("--min-group-n must be at least 2")
    if args.dataset == "all" and args.source_mode is not None:
        raise ValueError("--source-mode requires one concrete --dataset")
    if args.dataset == "all" and args.input_root is not None:
        raise ValueError("--input-root requires one concrete --dataset")

    project_root = find_project_root(args.project_root)
    datasets = DATASETS if args.dataset == "all" else (args.dataset,)
    summaries: list[dict[str, object]] = []
    for dataset in datasets:
        source_mode = args.source_mode or DEFAULT_SOURCE_MODES[dataset]
        input_root = (
            args.input_root.expanduser().resolve()
            if args.input_root is not None
            else project_root
            / "results"
            / "statistics"
            / "graphs"
            / dataset
            / source_mode
        )
        default_output = (
            project_root
            / "results"
            / "statistics"
            / "welch"
            / dataset
            / source_mode
        )
        if args.output_root is not None:
            explicit_output = args.output_root.expanduser().resolve()
            output_root = (
                explicit_output / dataset / source_mode
                if len(datasets) > 1
                else explicit_output
            )
        else:
            output_root = default_output

        required = (
            input_root / "graph_run_summary.json",
            input_root / "roi_summary.csv",
            input_root / "roi_profiles.npz",
        )
        missing = [path for path in required if not path.exists()]
        if missing:
            message = f"Missing full-mode graph outputs for {dataset}: {', '.join(map(str, missing))}"
            if args.skip_missing:
                print(f"[SKIP] {message}")
                continue
            raise FileNotFoundError(message)

        summaries.append(
            process_dataset(
                project_root=project_root,
                dataset=dataset,
                source_mode=source_mode,
                input_root=input_root,
                output_root=output_root,
                scalar_correction=args.scalar_correction,
                profile_correction=args.profile_correction,
                alpha=args.alpha,
                min_group_n=args.min_group_n,
                overwrite=args.overwrite,
            )
        )

    if not summaries:
        raise RuntimeError("No datasets were processed for Welch statistics.")

    batch_summary = {
        "requested_dataset": args.dataset,
        "processed_datasets": [summary["dataset"] for summary in summaries],
        "scalar_correction_method": args.scalar_correction,
        "profile_correction_method": args.profile_correction,
        "alpha": args.alpha,
        "minimum_group_n": args.min_group_n,
        "summaries": summaries,
    }
    batch_path = (
        project_root
        / "results"
        / "statistics"
        / "welch"
        / "welch_batch_summary.json"
    )
    batch_path.parent.mkdir(parents=True, exist_ok=True)
    batch_path.write_text(json.dumps(batch_summary, indent=2), encoding="utf-8")
    print(f"Batch summary: {batch_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
